if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED TEST_MODE)
    message(FATAL_ERROR "TEST_EXECUTABLE and TEST_MODE are required")
endif()

execute_process(COMMAND "${TEST_EXECUTABLE}" "${TEST_MODE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
    TIMEOUT 10)
if(NOT result MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "Native-only ${TEST_MODE} must exit with failure; got ${result}:\n${output}${error}")
endif()
if(TEST_MODE STREQUAL "step")
    set(expected_pc "80004008")
    set(expected_kind "uncovered AOT PC")
elseif(TEST_MODE STREQUAL "micro")
    set(expected_pc "80006004")
    set(expected_kind "unsupported AOT instruction")
    if(NOT error MATCHES "opcode=0x00000000")
        message(FATAL_ERROR "Unsupported instruction diagnostic lost its opcode:\n${error}")
    endif()
else()
    message(FATAL_ERROR "Unknown TEST_MODE: ${TEST_MODE}")
endif()
foreach(expected IN ITEMS "[AOT] ${expected_kind}: pc=0x${expected_pc}" "lr=0x80005000" "ctr=0x12345678")
    string(FIND "${error}" "${expected}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Native-only failure lacks '${expected}':\n${output}${error}")
    endif()
endforeach()
message(STATUS "PASS: ${TEST_MODE} fails with the offending native coverage address")
